services:
  db:
    image: mariadb:10.7.8-focal
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - 3306:3306 
    restart: always
    environment:
      - MARIADB_DATABASE=gnuboard5
      - MARIADB_USER=gnuboard5
      - MARIADB_PASSWORD=password5
      - MARIADB_ROOT_PASSWORD=password5
    expose:
      - 3306
    networks:
      - gnusite

  gnuboard:
    depends_on:
      - db
    image: gnuboard-fpm-apache:1.0.0
    container_name: gnuboard5
    ports:
      - 88:80
    restart: always
    volumes:
      - ./gnuboard5:/var/www/html
    networks:
      - gnusite

networks:
  gnusite:

volumes:
  db_data: